context:
  name: easy-eo
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easy_eo-${{ version }}.tar.gz
  sha256: f2c8cfa3167bf04c57f035be05ee462b828659e2aa453353f745e852432e3e08

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - rasterio >=1.4,<2
    - geopandas >=1.1,<2
    - numpy >=1.26,<3
    - matplotlib-base >=3.8

tests:
  - python:
      imports:
        - eeo
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/Tommy-Burns/easy-eo
  summary: A lightweight Earth Observation utilities library for chainable raster operations
  license: MIT
  license_file: LICENSE
  documentation: https://easy-eo.readthedocs.io/en/latest/
  repository: https://github.com/Tommy-Burns/easy-eo
extra:
  recipe-maintainers:
    - Tommy-Burns
